apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbb
  template:
    metadata:
      labels:
        app: bbb
    spec:
      containers:
        - name: bbb
          image: harbor.dev.cn/test-service/busybox:1.30.1
          tty: true






