apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: zgy-argo
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: harbor.dev.cn/test-service/busybox:1.30.1
          ports:
            - containerPort: 6379
              name: tcp6379
              protocol: TCP





