apiVersion: apps/v1
kind: Deployment
metadata:
  name: testpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testpod
  template:
    metadata:
      labels:
        app: testpod
    spec:
      containers:
        - name: testpod
          image: harbor.dev.cn/test-service/busybox:1.30.1
          tty: true






